---
apiVersion: v1
kind: Service
metadata:
  labels:
    appName: "hello-proxy-lagom-minimal-service"
  name: "hello-proxy-lagom-minimal-service"
spec:
  ports:
    - name: http
      port: 9000
      protocol: TCP
  selector:
    appName: "hello-proxy-lagom-minimal-service"
